-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 16:27:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petrol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petrol` ;

-- -----------------------------------------------------
-- Schema petrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petrol` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `petrol` ;

-- -----------------------------------------------------
-- Table `petrol`.`Gas_Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petrol`.`Gas_Station` ;

CREATE TABLE IF NOT EXISTS `petrol`.`Gas_Station` (
  `ID_GAS_STATION` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_GAS_STATION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrol`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petrol`.`Employee` ;

CREATE TABLE IF NOT EXISTS `petrol`.`Employee` (
  `ID_EMPLOYEE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `EXPERIENCE` INT NULL,
  `SALARY` DECIMAL(6,2) NOT NULL,
  `VACATION_DAYS` INT NULL,
  `ID_GAS_STATION` INT NOT NULL,
  PRIMARY KEY (`ID_EMPLOYEE`),
  INDEX `fk_radnici_pumpa_id_pumpa_idx` (`ID_GAS_STATION` ASC),
  CONSTRAINT `fk_employee_gas_station_id_gas_station`
    FOREIGN KEY (`ID_GAS_STATION`)
    REFERENCES `petrol`.`Gas_Station` (`ID_GAS_STATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrol`.`Fuel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petrol`.`Fuel` ;

CREATE TABLE IF NOT EXISTS `petrol`.`Fuel` (
  `ID_FUEL` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_FUEL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrol`.`Gas_Station_Fuel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petrol`.`Gas_Station_Fuel` ;

CREATE TABLE IF NOT EXISTS `petrol`.`Gas_Station_Fuel` (
  `ID_GAS_STATION_FUEL` INT NOT NULL AUTO_INCREMENT,
  `ID_GAS_STATION` INT NOT NULL,
  `ID_FUEL` INT NOT NULL,
  `AMOUNT_LITER` INT NOT NULL,
  PRIMARY KEY (`ID_GAS_STATION_FUEL`),
  INDEX `fk_gas_station_fuel_gas_station_id_gas_station_idx` (`ID_GAS_STATION` ASC),
  INDEX `fk_gas_station_fuel_fuel_id_fuel_idx` (`ID_FUEL` ASC),
  CONSTRAINT `fk_gas_station_fuel_gas_station_id_gas_station`
    FOREIGN KEY (`ID_GAS_STATION`)
    REFERENCES `petrol`.`Gas_Station` (`ID_GAS_STATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gas_station_fuel_fuel_id_fuel`
    FOREIGN KEY (`ID_FUEL`)
    REFERENCES `petrol`.`Fuel` (`ID_FUEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrol`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `petrol`.`User` ;

CREATE TABLE IF NOT EXISTS `petrol`.`User` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `SURNAME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `GAS_STATION_NAME` VARCHAR(255) NOT NULL,
  `ID_ROLE` INT NOT NULL DEFAULT '2',
  PRIMARY KEY (`ID_USER`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
